apiVersion: v1
kind: ResourceQuota
metadata:
  name: lingo-prod-quota
  namespace: lingo-prod
  labels:
    app.kubernetes.io/part-of: lingo-platform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "12"
    limits.memory: 16Gi
    requests.ephemeral-storage: 4Gi
    limits.ephemeral-storage: 10Gi
    count/pods: "30"
    count/services: "10"
    count/secrets: "25"
    count/configmaps: "25"
    persistentvolumeclaims: "5"
    services.loadbalancers: "0"
